default: &default
  adapter: postgresql
  encoding: utf-8
  username:  <%= Rails.application.config.database_username %>
  password:  <%= Rails.application.config.database_password %>
  host:      <%= Rails.application.config.database_host %>
  port:      <%= Rails.application.config.database_port %>
  database:  <%= Rails.application.config.database_name %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
