# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a752a06c0d008d955256c65c9802ef14a53c7e372bfc1d648bc3b37d73dabb2170a0e8b06dc8f299a40879c209ec05d9ce4e94e1da9534692f3b59d6c384866

test:
  secret_key_base: c93cc62f11e9d885549db89b231350672a50a2daeeb31becd143794919c28cbc4f66b23ac9f2c32dc2c6a9edabf87e1c429ad9cb74a85e9ddebb6790cfe8a435

# Do not keep production secrets in the repository,

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
